name: Deploy API to Azure Static Web App

on:
    push:
        branches: [main]
    workflow_dispatch:
        inputs:
            environment:
                type: environment
                description: "Environment to deploy to"
                required: true

jobs:
    build_and_deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20"
                  cache: "npm"
            - name: Install Dependencies
              run: npm install
            - name: Build project
              run: npm run build
            - name: Test project
              run: npm run test
            - name: Deploy to Azure Static Web App
              id: deploy
              uses: Azure/static-web-apps-deploy@v1
              with:
                  azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
                  action: "upload"
                  skip_app_build: true
                  app_location: "/build/client"
